[package]
name = "doctave-lib"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
alphanumeric-sort = "1.5.5"
ascii = "1.1"
bunt = "0.2.9"
bus = "2.4.1"
colorsys = "0.7.3"
crossbeam-channel = "0.5"
doctave-markdown = { git = "https://github.com/yonasBSD/doctave-markdown" }
elasticlunr-rs = { version = "3.0", default-features = false }
handlebars = "6.3.2"
http = "1.4"
include_dir = "0.7.4"
lazy_static = "1.5.0"
notify = "8.2.0"
rayon = "1.11"
scoped_threadpool = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
serde_yaml = "0.9"
tiny_http = "0.12"
tungstenite = { version = "0.28", default-features = false, features = ["handshake"] }
walkdir = "2.5.0"

[dev-dependencies]
indoc = "2.0.7"
